### ISSUE TITLE
Please support pathlib.Path objects

### ISSUE THREAD

**Issue by cdeil** [jupyter/nbformat#147]
Could you please add support for `pathlib.Path` objects in `nbformat.read` and `nbformat.write`?

See [pathlib](https://docs.python.org/3/library/pathlib.html) and [PEP 519](https://www.python.org/dev/peps/pep-0519/).

```
>>> import nbformat
>>> from pathlib import Path
>>> path = Path("tests/test2.ipynb")
>>> nb = nbformat.read(Path("tests/test2.ipynb"), as_version=4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/anaconda3/lib/python3.7/site-packages/nbformat/__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
AttributeError: 'PosixPath' object has no attribute 'read'
```

Looking at the implementation, it's clear why `pathlib.Path` isn't supported:

https://github.com/jupyter/nbformat/blob/b6b5a18e5a40d37f1cc0f71f65108288bdec9bb7/nbformat/__init__.py#L114-L141

But what is a good pattern to support `pathlib.Path` in addition?
Just an extra `if isinstance(fp, pathlib.Path)`, or is there a better way?

Note that the docstring still contains a caveat concerning Python 2, and `py3compat` is used. Probably that could be removed now.

I wanted to send a PR, but it wasn't clear to me how to write it. If you comment or point out an example how you do this in other places in the Jupyter codebase, I can take a shot at it.

**Comment by bollwyvl** [comment]
> But what is a good pattern 

Perhaps we dig a bit deeper into [PEP519](https://www.python.org/dev/peps/pep-0519/#backwards-compatibility)

>> Libraries wishing to support path objects and a version of Python prior to Python 3.6 and the existence of os.fspath() can use the idiom of `path.__fspath__() if hasattr(path, "__fspath__") else path`.

Other feature requests:
- https://github.com/paramiko/paramiko/issues/1252
- https://github.com/gitpython-developers/GitPython/pull/780
- https://github.com/pytorch/pytorch/pull/18562
- https://github.com/spotify/luigi/pull/2548

> other places in the Jupyter codebase

I don't think we have a lot of examples of supporting `Path` elsewhere, and there are still some caveats with how they (don't) work on 3.5, but on the whole it would be great to support them... though I think a 3.6+ adoption would be most appropriate. We may want to look to _other_ places that support them for inspiration... do you have any in mind?

Jupyter-adjacent things:
- https://github.com/Zsailer/traitlets_paths
- https://github.com/quantopian/serializable-traitlets
- https://github.com/ipython/ipython/issues/10427
- https://github.com/chrisjsewell/ipypublish
